### Criar artista
POST http://localhost:8080/api/v1/artistas
Content-Type: application/json

{
  "nome": "Djavan"
}

### Listar artistas (paginado)
GET http://localhost:8080/api/v1/artistas?page=0&size=10&sort=nome,asc

### Buscar artista por id
GET http://localhost:8080/api/v1/artistas/1

### Atualizar artista
PUT http://localhost:8080/api/v1/artistas/1
Content-Type: application/json

{
  "nome": "Serj Tankian"
}

### Remover artista
DELETE http://localhost:8080/api/v1/artistas/1

### Criar album
POST http://localhost:8080/api/v1/albuns
Content-Type: application/json

{
  "titulo": "The Rough Dog"
}

### Listar álbuns
GET http://localhost:8080/api/v1/albuns

### Vincular álbum a um artista
POST http://localhost:8080/api/v1/artistas/1/albuns/3

### Buscar detalhe
GET http://localhost:8080/api/v1/artistas/1

### Desvincular álbum de um artista
DELETE http://localhost:8080/api/v1/artistas/1/albuns/1

### Teste de erro 404
GET http://localhost:8080/api/v1/artistas/999999

### Erro 400 com validação
POST http://localhost:8080/api/v1/artistas
Content-Type: application/json

{
  "nome": ""
}