spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/musicapi
    username: musicapi
    password: musicapi
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
